---

# Pre-commit framework manifest. Install with `pip install pre-commit` or through distrib package manager (probably not up to date though)
# Install new hooks with `pre-commit install`
# Update hooks revs with `pre-commit autoupdate`; if unsure, set 'latest' and run this command to grab the last one
# Manually run with `pre-commit run --all-files [<hookId>]`
# Hooks can temporarily be disabled with envvar SKIP : `SKIP=<hookId> git commit -m "<message>"` Also works with `pre-commit run`

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-symlinks

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.9
    hooks:
      - id: pymarkdown
        args:
          - --disable-rules
          - line-length,first-line-heading,first-line-h1,no-inline-html,ul-indent,single-title,single-h1,no-space-in-code,no-reversed-links,commands-show-output
          - scan
