FROM pandoc/latex:"{{ resumemake_image_tag }}"
ENV DEBIAN_FRONTEND noninteractive
RUN apt update; apt install -y make texlive wkhtmltopdf \
  && adduser --quiet --gecos "" --disabled-password --no-create-home "{{ ansible_user_id }}"
ENV TEXMF /usr/share/texmf-dist
USER "{{ ansible_user_id }}"
ENTRYPOINT {{resumemake_image_entrypoint}}
