OUT_DIR=/tmp
IN_DIR=resumes
STYLES_DIR=styles
CSS_STYLE="{{ css_style }}"

all: html pdf

html: init
	for f in $(IN_DIR)/*.md; do \
		FILE_NAME=`basename $$f | sed 's/.md//g'`; \
		echo $$FILE_NAME.html; \
		pandoc --standalone --include-in-header $(STYLES_DIR)/$(CSS_STYLE).css \
			--lua-filter=pdc-links-target-blank.lua \
			--from markdown --to html \
			--output $(OUT_DIR)/$$FILE_NAME.html $$f \
			--metadata pagetitle=$$FILE_NAME;\
	done

#pdf: init
#	for f in $(IN_DIR)/*.md; do \
#		FILE_NAME=`basename $$f | sed 's/.md//g'`; \
#		echo $$FILE_NAME.pdf; \
#		pandoc --standalone -t html5 --from html --to pdf $(OUT_DIR)/$$FILE_NAME.html --include-in-header $(STYLES_DIR)/$(CSS_STYLE).css -o $(OUT_DIR)/$$FILE_NAME.pdf --metadata title=$$FILE_NAME $$f; \
#	done

pdf: init
	for f in $(IN_DIR)/*.md; do \
		FILE_NAME=`basename $$f | sed 's/.md//g'`; \
		echo $$FILE_NAME.pdf; \
		wkhtmltopdf $(OUT_DIR)/$$FILE_NAME.html $(OUT_DIR)/$$FILE_NAME.pdf; \
	done

init: dir version

dir:
	mkdir -p $(OUT_DIR)

version:
	PANDOC_VERSION=`pandoc --version | head -1 | cut -d' ' -f2 | cut -d'.' -f1`; \
	if [ "$$PANDOC_VERSION" -eq "2" ]; then \
		SMART=-smart; \
	else \
		SMART=--smart; \
	fi \

clean:
	rm -f $(OUT_DIR)/*
